[package]
name = "http-get"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
